# Generated by Django 4.1.7 on 2023-03-19 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_remove_cart_total_price_alter_cart_product_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={},
        ),
        migrations.AlterModelOptions(
            name='manufacturer',
            options={},
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='product',
            new_name='prod',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='quantity',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
