# Generated by Django 4.1.7 on 2023-03-20 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_alter_cart_options_alter_manufacturer_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'Cart', 'verbose_name_plural': 'Carts'},
        ),
    ]
