# Generated by Django 4.1.7 on 2023-03-20 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0006_alter_cart_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Manufacturer',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='size',
            new_name='desc',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='prod',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='product',
            name='manufactur',
        ),
        migrations.RemoveField(
            model_name='product',
            name='time_create',
        ),
        migrations.AddField(
            model_name='cart',
            name='descript',
            field=models.ManyToManyField(related_name='descriptions', to='category.product'),
        ),
        migrations.AddField(
            model_name='cart',
            name='product1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cartprod', to='category.product'),
        ),
    ]
