# Generated by Django 4.1.7 on 2023-03-20 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0007_delete_manufacturer_rename_size_product_desc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='allprice',
            field=models.IntegerField(default=0, max_length=10, null=True),
        ),
    ]
