# Generated by Django 4.1.7 on 2023-03-20 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0008_cart_allprice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='product1',
            new_name='product',
        ),
    ]
