# Generated by Django 4.1.7 on 2023-03-20 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0009_rename_product1_cart_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cat',
        ),
        migrations.AlterField(
            model_name='cart',
            name='descript',
            field=models.ManyToManyField(to='category.product'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
